//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedLabApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IDService { get; set; }
        public int IDOrderStatus { get; set; }
        public string LeadTime { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Service Service { get; set; }
    }
}
