//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedLabApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int PSerias { get; set; }
        public int PNumder { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int PolicyNumber { get; set; }
        public int IDPolicyType { get; set; }
        public int IDInsuranceCompany { get; set; }
        public string IDRole { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual PolicyType PolicyType { get; set; }
        public virtual Role Role { get; set; }
    }
}
