//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMedLabApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRendered
    {
        public int ID { get; set; }
        public int IDService { get; set; }
        public System.DateTime Issued { get; set; }
        public int IDLaborant { get; set; }
        public int IDAnalyzer { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Laborant Laborant { get; set; }
    }
}
